# Generated by Django 5.2.4 on 2026-02-26 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_user_id', models.IntegerField(blank=True, null=True)),
                ('component_type', models.CharField(choices=[('automatic', 'Автоматические выключатели'), ('transformer', 'Трансформаторы'), ('counter', 'Счетчики')], max_length=20)),
                ('article', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='detection_results/')),
                ('object_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='ID объекта')),
                ('group_index', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('session_key', models.CharField(db_index=True, default='', max_length=40)),
                ('result_id', models.CharField(db_index=True, default='', max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recognition_images_component',
                'indexes': [models.Index(fields=['session_key', 'result_id'], name='comp_session_result_idx'), models.Index(fields=['created_at'], name='comp_created_at_idx')],
            },
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('result_id', models.CharField(max_length=100, unique=True)),
                ('image_base64', models.TextField()),
                ('search_results', models.JSONField(blank=True, null=True)),
                ('detected_data', models.JSONField()),
                ('edited_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('name', models.CharField(default='Без названия', max_length=255, verbose_name='Название')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Избранное')),
                ('old_user_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recognition_images_detectionresult',
                'indexes': [models.Index(fields=['session_key', 'result_id'], name='detect_session_result_idx'), models.Index(fields=['created_at'], name='detect_created_at_idx')],
            },
        ),
    ]
