# Generated by Django 5.2.4 on 2026-02-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognition_images', '0001_initial'),
    ]

    operations = [
    ]
