# Generated by Django 5.2.4 on 2025-07-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition_images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='image_path',
        ),
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='detection_results/'),
        ),
    ]
