# Generated by Django 5.2.4 on 2026-03-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition_images', '0002_manual_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionresult',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
