# Generated by Django 5.2.4 on 2025-07-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition_images', '0002_remove_component_image_path_component_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='object_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ID объекта'),
        ),
    ]
