# Generated by Django 5.2.4 on 2025-07-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition_images', '0003_add_object_id_to_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='group_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
